services:
  mongo:
    image: mongo:7
    container_name: digitalme-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build: 
      context: ./DigitalMeAPI
    container_name: digitalme-api
    ports:
      - "7777:7777"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/digitalme
    volumes:
      - ./DigitalMeAPI:/app
    command: npm run dev

  web:
    build:
      context: ./DigitalMe
    container_name: digitalme-web
    ports:
      - "1234:1234"
    depends_on:
      - api
    volumes:
      - ./DigitalMe:/app
    command: npm run dev

volumes:
  mongo-data:
